#include "breder.h"
b_bni_class_define(b_bni_class_object_id, object_id, "breder.lang.standard.Object")
b_bni_class_define(b_bni_class_throw_id, throw_id, "breder.lang.standard.Throw")
b_bni_class_define(b_bni_class_string_id, string_id, "breder.lang.standard.String")
b_bni_class_define(b_bni_class_number_id, number_id, "breder.lang.standard.Number")
b_bni_class_define(b_bni_class_integer_id, integer_id, "breder.lang.standard.Integer")
b_bni_class_define(b_bni_class_natural_id, natural_id, "breder.lang.standard.Natural")
b_bni_class_define(b_bni_class_index_id, index_id, "breder.lang.standard.Index")
b_bni_class_define(b_bni_class_boolean_id, boolean_id, "breder.lang.standard.Boolean")
b_bni_class_define(b_bni_class_class_id, class_id, "breder.lang.standard.Class")
b_bni_class_define(b_bni_class_outofmemoryexception_id, outofmemoryexception_id, "breder.lang.standard.OutOfMemoryRuntimeException")
b_bni_class_define(b_bni_class_classnotfoundexception_id, classnotfoundexception_id, "breder.lang.standard.ClassNotFoundRuntimeException")
b_bni_class_define(b_bni_class_method_id, method_id, "breder.lang.standard.Method")
b_bni_class_define(b_bni_class_arraylist_id, arraylist_id, "breder.util.standard.ArrayList")
b_bni_class_define(b_bni_class_indexoutofboundsexception_id, indexoutofboundsexception_id, "breder.util.standard.IndexOutOfBoundsRuntimeException")
b_bni_class_define(b_bni_class_compileexception_id, compileexception_id, "breder.lang.standard.IndexCompileException")
b_bni_class_define(b_bni_class_ilist_id, ilist_id, "breder.util.IList")
b_bni_class_define(b_bni_class_iarray_id, iarray_id, "breder.util.IArray")
b_bni_class_define(b_bni_class_iresource_id, iresource_id, "breder.io.IResource")
b_bni_class_define(b_bni_class_ifolder_id, ifolder_id, "breder.io.IFolder")
b_bni_class_define(b_bni_class_ifile_id, ifile_id, "breder.io.IFile")
b_bni_class_define(b_bni_class_resource_id, resource_id, "breder.io.local.standard.LocalResource")
b_bni_class_define(b_bni_class_folder_id, folder_id, "breder.io.local.standard.LocalFolder")
b_bni_class_define(b_bni_class_file_id, file_id, "breder.io.local.standard.LocalFile")
b_bni_class_define(b_bni_class_iframe_id, iframe_id, "breder.gui.IFrame")
b_bni_class_define(b_bni_class_opengl_id, opengl_id, "breder.gui.Opengl")
b_bni_class_define(b_bni_class_glframe_id, glframe_id, "breder.gui.GlFrame")
b_bni_class_define(b_bni_class_iglframe_id, iglframe_id, "breder.gui.opengl.IGlFrame")
b_bni_class_define(b_bni_class_sizeable_id, sizeable_id, "breder.gui.Sizeable")
b_bni_class_define(b_bni_class_titleable_id, titleable_id, "breder.gui.Titleable")
b_bni_class_define(b_bni_class_vector2d_id, vector2d_id, "breder.math.Vector2D")
b_bni_class_define(b_bni_class_vector3d_id, vector3d_id, "breder.math.Vector3D")
b_bni_class_define(b_bni_class_ioexception_id, ioexception_id, "breder.io.IOException")
b_bni_class_define(b_bni_class_parseexception_id, class_parseexception_id, "breder.exception.ParseException")
b_bni_method_define(b_bni_method_iframe_paint_id, iframe_paint_id, b_bni_class_iframe_id, "() paint (breder.gui.IGraphic)")
b_bni_method_define(b_bni_method_ioexception_init_id, ioexception_init_id, b_bni_class_ioexception_id, "() IOException ()")
b_bni_method_define(b_bni_method_arraylist_init_id, arraylist_init_id, b_bni_class_arraylist_id, "() ArrayList ()")
b_bni_method_define(b_bni_method_resource_init_id, resource_init_id, b_bni_class_resource_id, "() LocalResource (breder.lang.standard.String)")
b_bni_method_define(b_bni_method_folder_init_id, folder_init_id, b_bni_class_folder_id, "() LocalFile (breder.lang.standard.String)")
b_bni_method_define(b_bni_method_file_init_id, file_init_id, b_bni_class_file_id, "() LocalFolder (breder.lang.standard.String)")
b_bni_method_define(b_bni_method_ilist_add_id, ilist_add_id, b_bni_class_ilist_id, "(breder.util.IList<<E breder.lang.standard.Object>>) add (<E breder.lang.standard.Object>)")
b_bni_method_define(b_bni_method_ilist_size_id, ilist_size_id, b_bni_class_iarray_id, "(breder.lang.standard.Natural) size ()")
b_bni_method_define(b_bni_method_iresource_getname_id, iresource_getname_id, b_bni_class_iresource_id, "(breder.lang.standard.String) getName ()")
b_bni_method_define(b_bni_method_iresource_getabsolutename_id, iresource_getabsolutename_id, b_bni_class_iresource_id, "(breder.lang.standard.String) getAbsoluteName ()")
b_bni_method_define(b_bni_method_resource_getname_id, resource_getname_id, b_bni_class_resource_id, "(breder.lang.standard.String) getName ()")
b_bni_method_define(b_bni_method_resource_getabsolutename_id, resource_getabsolutename_id, b_bni_class_resource_id, "(breder.lang.standard.String) getAbsoluteName ()")
b_bni_method_define(b_bni_method_object_tostring_id, object_tostring_id, b_bni_class_object_id, "(breder.lang.standard.String) toString ()")
b_bni_method_define(b_bni_method_object_hashcode_id, object_hashcode_id, b_bni_class_object_id, "(breder.lang.standard.Integer) hashcode ()")
b_bni_method_define(b_bni_method_object_finalize_id, object_finalize_id, b_bni_class_object_id, "() finalize ()")
b_bni_method_define(b_bni_method_object_operatorequal_id, object_operatorequal_id, b_bni_class_object_id, "(breder.lang.standard.Boolean) operatorEqual (breder.lang.standard.Object)")
b_bni_method_define(b_bni_method_classnotfoundexception_init_id, classnotfoundexception_init_id, b_bni_class_classnotfoundexception_id, "() ClassNotFoundRuntimeException ()")
b_bni_method_define(b_bni_method_indexoutofboundsruntimeexception_init_id, indexoutofboundsexception_init_id, b_bni_class_indexoutofboundsexception_id, "() IndexOutOfBoundsRuntimeException ()")
b_bni_method_define(b_bni_method_outofmemoryruntimeexception_init_id, outofmemoryexception_init_id, b_bni_class_outofmemoryexception_id, "() OutOfMemoryRuntimeException ()")
b_bni_method_define(b_bni_method_glframe_reshape_id, glframe_reshape_id, b_bni_class_glframe_id, "() reshape (breder.lang.standard.Number,breder.lang.standard.Number)")
b_bni_method_define(b_bni_method_glframe_init_id, glframe_init_id, b_bni_class_glframe_id, "() init ()")
b_bni_method_define(b_bni_method_glframe_keypress_id, glframe_keypress_id, b_bni_class_glframe_id, "() keyPress (breder.lang.standard.Number,breder.lang.standard.Number,breder.lang.standard.Number)")
b_bni_method_define(b_bni_method_glframe_keyrelease_id, glframe_keyrelease_id, b_bni_class_glframe_id, "() keyRelease (breder.lang.standard.Number,breder.lang.standard.Number,breder.lang.standard.Number)")
b_bni_method_define(b_bni_method_glframe_paint_id, glframe_paint_id, b_bni_class_glframe_id, "() paint ()")
b_bni_method_define(b_bni_method_iglframe_fps_id, iglframe_fps_id, b_bni_class_iglframe_id, "(breder.lang.standard.Natural) getFps ()")
b_bni_method_define(b_bni_method_iglframe_width_id, iglframe_width_id, b_bni_class_iglframe_id, "(breder.lang.standard.Natural) getWidth ()")
b_bni_method_define(b_bni_method_iglframe_height_id, iglframe_height_id, b_bni_class_iglframe_id, "(breder.lang.standard.Natural) getHeight ()")
b_bni_method_define(b_bni_method_iglframe_title_id, iglframe_title_id, b_bni_class_iglframe_id, "(breder.lang.standard.String) getTitle ()")
b_bni_method_define(b_bni_method_sizeable_setsize_id, sizeable_setsize_id, b_bni_class_sizeable_id, "() setSize (breder.lang.standard.Number,breder.lang.standard.Number)")
b_bni_method_define(b_bni_method_sizeable_getwidth_id, sizeable_getwidth_id, b_bni_class_sizeable_id, "(breder.lang.standard.Number) getWidth ()")
b_bni_method_define(b_bni_method_sizeable_getheight_id, sizeable_getheight_id, b_bni_class_sizeable_id, "(breder.lang.standard.Number) getHeight ()")
b_bni_method_define(b_bni_method_titleable_gettitle_id, titleable_gettitle_id, b_bni_class_titleable_id, "(breder.lang.standard.String) getTitle ()")
b_bni_method_define(b_bni_method_vector2d_init_id, vector2d_init_id, b_bni_class_vector2d_id, "() Vector2D (breder.lang.standard.Number,breder.lang.standard.Number)")
b_bni_method_define(b_bni_method_vector3d_init_id, vector3d_init_id, b_bni_class_vector3d_id, "() Vector3D (breder.lang.standard.Number,breder.lang.standard.Number,breder.lang.standard.Number)")
b_bni_method_define(b_bni_method_vector2d_getx_id, vector2d_getx_id, b_bni_class_vector2d_id, "(breder.lang.standard.Number) getX ()")
b_bni_method_define(b_bni_method_vector2d_gety_id, vector2d_gety_id, b_bni_class_vector2d_id, "(breder.lang.standard.Number) getY ()")
b_bni_method_define(b_bni_method_vector3d_getz_id, vector3d_getz_id, b_bni_class_vector3d_id, "(breder.lang.standard.Number) getZ ()")
b_bni_method_define(b_bni_method_vector3d_length_id, vector3d_length_id, b_bni_class_vector3d_id, "(breder.lang.standard.Number) length ()")
b_bni_method_define(b_bni_method_parseexception_init_id, method_parseexception_id, b_bni_class_parseexception_id, "() ParseException ()")
b_bni_method_define(b_bni_method_compileexception_init_id, method_compileexception_id, b_bni_class_compileexception_id, "() CompileException ()")
